In [16]:
#%matplotlib inline
import matplotlib
import pandas as pd
import os

In [17]:
headlines = pd.read_csv(os.path.join('output.csv'))
headlines.head()

,Unnamed: 0,Headline,Read/Fake,Character Count,Word Count,Upper Characters,Lower Case Characters,SpecialChar Count
0,0,#2816: Clinton Pride’s 8(a) Pig Farm Bridge – ...,fake,97,16,13,56,8
1,1,#2817: Serco's Zulu Starnet Blackmail – Clinto...,fake,88,15,11,51,7
2,2,Roger Stone update on Stop the Steal exit poll...,fake,456,72,14,358,13
3,3,#2818: Serco's Zulu Bridge To Mumbai Pig Farm ...,fake,91,17,12,47,8
4,4,Trump Advocates the American People's Control ...,fake,66,9,9,46,3

In [19]:
# Assign X (data) and y (target)
# This makes all data on the X axis and only "Label" on Y axis. Otherwise would not be independent labels
headlines.drop('Headline', axis=1, inplace=True)
X = headlines.drop("Read/Fake", axis=1)
y = headlines["Read/Fake"]
print(X.shape, y.shape)

(39791, 6) (39791,)

In [20]:
X.head()

,Unnamed: 0,Character Count,Word Count,Upper Characters,Lower Case Characters,SpecialChar Count
0,0,97,16,13,56,8
1,1,88,15,11,51,7
2,2,456,72,14,358,13
3,3,91,17,12,47,8
4,4,66,9,9,46,3

In [21]:
import sklearn

## Split our data into training and testing

In [22]:
# Split the data using train_test_split
# Random state 1 will get you to same place
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

## Create a Logistic Regression Model

In [23]:
# Create a logistic regression model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [24]:
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

## Fit (train) or model using the training data

In [25]:
# Fit the model to the data
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [26]:
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

## Validate the model using the test data

In [27]:
# Print the accuracy for the test data
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.7652317524144616
Testing Data Score: 0.7678003015580499

## Make predictions

In [28]:
# Make predictions using the X_test and y_test data
# Print at least 10 predictions vs their actual labels
from sklearn.metrics import mean_squared_error, r2_score
# predicted_train = classifier.predict(X_train)
# predicted_test = classifier.predict(X_test)
predictions = classifier.predict(X_test)
#{predictions[:10]}
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index

<bound method DataFrame.reset_index of       Prediction Actual
12300       fake   real
23033       real   fake
26860       real   fake
14229       fake   real
27707       real   fake
1824        fake   fake
25143       real   fake
4407        fake   fake
16705       real   real
33067       real   real
23123       real   fake
6051        fake   fake
36000       real   real
3320        fake   fake
28441       fake   fake
33183       real   real
2818        fake   fake
9101        fake   fake
1799        fake   fake
36530       real   real
22823       real   real
37501       real   real
18857       real   real
28711       fake   fake
10001       fake   fake
35131       real   real
4401        fake   fake
19039       real   real
20108       real   real
32799       real   real
...          ...    ...
39370       real   real
31669       real   real
22366       real   real
3311        fake   fake
1276        fake   fake
24236       real   fake
13850       fake   real
31013       real   real
13716       real   real
27642       fake   fake
4578        fake   fake
18835       real   real
4686        fake   fake
35574       real   real
5474        fake   fake
30269       real   real
8600        fake   fake
15917       fake   real
21285       fake   real
14107       real   real
3837        fake   fake
12832       fake   real
7073        fake   fake
19203       real   real
11102       fake   real
28536       fake   fake
22781       real   real
1439        fake   fake
38523       real   real
31762       real   real

[11938 rows x 2 columns]>

In [29]:
predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   ['fake' 'real' 'real' 'fake' 'real' 'fake' 'real' 'fake' 'real' 'real']
First 10 Actual labels: ['real', 'fake', 'fake', 'real', 'fake', 'fake', 'fake', 'fake', 'real', 'real']

In [30]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

      Prediction Actual
0           fake   real
1           real   fake
2           real   fake
3           fake   real
4           real   fake
5           fake   fake
6           real   fake
7           fake   fake
8           real   real
9           real   real
10          real   fake
11          fake   fake
12          real   real
13          fake   fake
14          fake   fake
15          real   real
16          fake   fake
17          fake   fake
18          fake   fake
19          real   real
20          real   real
21          real   real
22          real   real
23          fake   fake
24          fake   fake
25          real   real
26          fake   fake
27          real   real
28          real   real
29          real   real
...          ...    ...
11908       real   real
11909       real   real
11910       real   real
11911       fake   fake
11912       fake   fake
11913       real   fake
11914       fake   real
11915       real   real
11916       real   real
11917       fake   fake
11918       fake   fake
11919       real   real
11920       fake   fake
11921       real   real
11922       fake   fake
11923       real   real
11924       fake   fake
11925       fake   real
11926       fake   real
11927       real   real
11928       fake   fake
11929       fake   real
11930       fake   fake
11931       real   real
11932       fake   real
11933       fake   fake
11934       real   real
11935       fake   fake
11936       real   real
11937       real   real

[11938 rows x 2 columns]

## Confusion Matrix

In [31]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predictions)

tn, fp, fn, tp = confusion_matrix(y_test, predictions).ravel()
print(f"tn: {tn:3d}   fp: {fp:3d}")
print(f"fn: {fn:3d}   tp: {tp:3d}")

tn: 3475   fp: 1507
fn: 1265   tp: 5691